// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpeedokuRoyaleServer.Models.DbContexts;

#nullable disable

namespace SpeedokuRoyaleServer.Migrations
{
    [DbContext(typeof(MariaDbContext))]
    [Migration("20220921190945_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SpeedokuRoyaleServer.Models.Inventory", b =>
                {
                    b.Property<ulong?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("ItemId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("PlayerId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("SpeedokuRoyaleServer.Models.Item", b =>
                {
                    b.Property<ulong?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("SpeedokuRoyaleServer.Models.MultiplayerGame", b =>
                {
                    b.Property<ulong?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.ToTable("MultiplayerGames");
                });

            modelBuilder.Entity("SpeedokuRoyaleServer.Models.MultiplayerSession", b =>
                {
                    b.Property<ulong?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("MultiplayerGameId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("PlayerId")
                        .HasColumnType("bigint unsigned");

                    b.Property<uint>("Score")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("MultiplayerGameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("MultiplayerSessions");
                });

            modelBuilder.Entity("SpeedokuRoyaleServer.Models.Player", b =>
                {
                    b.Property<ulong?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("SpeedokuRoyaleServer.Models.SingleplayerGame", b =>
                {
                    b.Property<ulong?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.ToTable("SingleplayerGames");
                });

            modelBuilder.Entity("SpeedokuRoyaleServer.Models.SingleplayerSession", b =>
                {
                    b.Property<ulong?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("PlayerId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("SingleplayerGameId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SingleplayerGameId");

                    b.ToTable("SingleplayerSessions");
                });

            modelBuilder.Entity("SpeedokuRoyaleServer.Models.TodoItem", b =>
                {
                    b.Property<ulong?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");
                });

            modelBuilder.Entity("SpeedokuRoyaleServer.Models.Inventory", b =>
                {
                    b.HasOne("SpeedokuRoyaleServer.Models.Item", "Item")
                        .WithMany("Inventories")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpeedokuRoyaleServer.Models.Player", "Player")
                        .WithMany("Inventories")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("SpeedokuRoyaleServer.Models.MultiplayerSession", b =>
                {
                    b.HasOne("SpeedokuRoyaleServer.Models.MultiplayerGame", "MultiplayerGame")
                        .WithMany("MultiplayerSessions")
                        .HasForeignKey("MultiplayerGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpeedokuRoyaleServer.Models.Player", "Player")
                        .WithMany("MultiplayerSessions")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MultiplayerGame");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("SpeedokuRoyaleServer.Models.SingleplayerSession", b =>
                {
                    b.HasOne("SpeedokuRoyaleServer.Models.Player", "Player")
                        .WithMany("SingleplayerSessions")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpeedokuRoyaleServer.Models.SingleplayerGame", "SingleplayerGame")
                        .WithMany("SingleplayerSessions")
                        .HasForeignKey("SingleplayerGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("SingleplayerGame");
                });

            modelBuilder.Entity("SpeedokuRoyaleServer.Models.Item", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("SpeedokuRoyaleServer.Models.MultiplayerGame", b =>
                {
                    b.Navigation("MultiplayerSessions");
                });

            modelBuilder.Entity("SpeedokuRoyaleServer.Models.Player", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("MultiplayerSessions");

                    b.Navigation("SingleplayerSessions");
                });

            modelBuilder.Entity("SpeedokuRoyaleServer.Models.SingleplayerGame", b =>
                {
                    b.Navigation("SingleplayerSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
